pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME' // Ensure this matches the name of the Maven installation in Jenkins
    }


    parameters {
        string(name: 'dev/calmac', defaultValue: 'main', description: 'Branch to build')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the specified branch from the Git repository
                git branch: "${params.dev/calmac}", url: 'http://muhammad.iftikhar@192.168.1.15:7990/scm/ebr4_sc/test-automation.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'mvn test -Dsurefire.suiteXmlFiles=CalmacSanity.xml'
                }
            }
        }
        stage('Publish Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            mail to: 'your-email@example.com',
                 subject: "Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) - ${currentBuild.currentResult}",
                 body: "Check the build results at ${env.BUILD_URL}"
        }
    }
}